Feat/adding active users aggregates dim config
mozilla/dim pull request #39
Opened 2022-11-09 18:12 UTC by kik-kik

# Feat/adding active users aggregates dim config

2022-11-10 10:02 UTC, kik-kik commented
WIP until Lucia is back and we can confirm if there is anything else we should be watching out for.

2022-11-15 10:53 UTC, gkabbz approved these changes
Looks like we have tests for both active_users_aggregates view as well as the active_users_aggregates_v1 table. Do we need both? Wouldn't that kick off two separate alerts for the same issue?

2022-11-15 11:40 UTC, kik-kik commented
@gkabbz good point, not sure why both were there. I removed the config for the table directly.

2022-11-15 11:40 UTC, kik-kik commented on dim_checks/moz-fx-data-shared-prod/telemetry/active_users_aggregates/dim_checks.yaml
> +          - first_seen_year: "> 2020"
@lucia-vargas-a is this a correct assumption? It seems we have a lot of values which would be less that that.

2022-11-21 14:54 UTC, lucia-vargas-a commented on dim_checks/moz-fx-data-shared-prod/telemetry/active_users_aggregates/dim_checks.yaml
> +          - submission_date  # probably don't need this since we run checks on a single partition at a time
No, there are several values for these same combination.

2022-11-21 14:59 UTC, lucia-vargas-a commented on dim_checks/moz-fx-data-shared-prod/telemetry/active_users_aggregates/dim_checks.yaml
> +        expected_values:
Some missing values? See [the full list here](https://github.com/mozilla/dim/blob/2fd107e4349d8fc70ce0538a905cd2ac9430a188/dim_checks/moz-fx-data-shared-prod/telemetry/unified_metrics/dim_checks.yaml#L74).

2022-11-21 15:03 UTC, lucia-vargas-a requested changes
Missing values and comments in files.

2022-11-21 15:22 UTC, kik-kik commented on dim_checks/moz-fx-data-shared-prod/telemetry/active_users_aggregates/dim_checks.yaml
> +          - submission_date  # probably don't need this since we run checks on a single partition at a time
What combination should give us a unique entry?

2022-11-21 16:05 UTC, kik-kik commented on dim_checks/moz-fx-data-shared-prod/telemetry/active_users_aggregates/dim_checks.yaml
> +          - submission_date  # probably don't need this since we run checks on a single partition at a time
@lucia-vargas-a

2022-11-23 13:56 UTC, merged